/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#00685f",
        "on-primary": "#ffffff",
        "primary-container": "#008378",
        "on-primary-container": "#f4fffc",
        "primary-fixed": "#89f5e7",
        "primary-fixed-dim": "#6bd8cb",
        "on-primary-fixed": "#00201d",
        "on-primary-fixed-variant": "#005049",
        secondary: "#855300",
        "on-secondary": "#ffffff",
        "secondary-container": "#fea619",
        "on-secondary-container": "#684000",
        "secondary-fixed": "#ffddb8",
        "secondary-fixed-dim": "#ffb95f",
        "on-secondary-fixed": "#2a1700",
        "on-secondary-fixed-variant": "#653e00",
        tertiary: "#38645c",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#517d75",
        "on-tertiary-container": "#f4fffb",
        "tertiary-fixed": "#bdece2",
        "tertiary-fixed-dim": "#a2d0c6",
        "on-tertiary-fixed": "#00201c",
        "on-tertiary-fixed-variant": "#224e47",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#f8f9ff",
        "on-background": "#121c2a",
        surface: "#f8f9ff",
        "on-surface": "#121c2a",
        "surface-variant": "#d9e3f6",
        "on-surface-variant": "#3d4947",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e6eeff",
        "surface-container-high": "#dee9fc",
        "surface-container-highest": "#d9e3f6",
        "surface-dim": "#d0dbed",
        "surface-bright": "#f8f9ff",
        "surface-tint": "#006a61",
        "inverse-surface": "#27313f",
        "inverse-on-surface": "#eaf1ff",
        "inverse-primary": "#6bd8cb",
        outline: "#6d7a77",
        "outline-variant": "#bcc9c6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        card: "12px", // ← TAMBAH: untuk rounded-card
        "ui-element": "8px", // ← TAMBAH: untuk rounded-ui-element
        full: "9999px",
      },
      spacing: {
        base: "8px", // ← TAMBAH: untuk gap-base
        "nav-item-height": "56px", // ← TAMBAH: untuk h-nav-item-height
        "touch-target-min": "48px",
        gutter: "16px",
        "margin-mobile": "20px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "24px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "36px", fontWeight: "700" },
        ],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-lg": [
          "14px",
          { lineHeight: "20px", fontWeight: "600", letterSpacing: "0.05em" }, // ← FIX: tambah letterSpacing
        ],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
